// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aioltbsxwldyexdkqjup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpb2x0YnN4d2xkeWV4ZGtxanVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDcyMjksImV4cCI6MjA2NjQyMzIyOX0.VxU-hJq0EFGDgR-mh6y0Il47EQY8SAkYPz8SrG0z3pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});